(Pandas df.describe())
> summary(my_data[, c("actual_price", "discounted_price", "discount_percentage", "rating")])
  actual_price    discounted_price discount_percentage     rating     
 Min.   :    39   Min.   :   39    Min.   : 0.00       Min.   :2.000  
 1st Qu.:   800   1st Qu.:  325    1st Qu.:32.00       1st Qu.:4.000  
 Median :  1650   Median :  799    Median :50.00       Median :4.100  
 Mean   :  5445   Mean   : 3125    Mean   :47.69       Mean   :4.097  
 3rd Qu.:  4295   3rd Qu.: 1999    3rd Qu.:63.00       3rd Qu.:4.300  
 Max.   :139900   Max.   :77990    Max.   :94.00       Max.   :5.000  
                                                       NA's   :1      
> #Q1. Do discounts increase during the sale?
> #avrage and maximum
> mean(my_data$discount_percentage, na.rm = TRUE)
[1] 47.69147
> max(my_data$discount_percentage, na.rm = TRUE)
[1] 94
> #Q2. Do you look at the ratings?
> cor(my_data$discount_percentage, my_data$rating, use = "complete.obs")
[1] -0.1553754
> # Which category offers the highest discount?
> aggregate(discount_percentage ~ category, data = my_data, FUN = mean)
                                                                                                                   category
1                                                    Car&Motorbike|CarAccessories|InteriorAccessories|AirPurifiers&Ionizers
2                                                   Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters
3                                           Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets
4                                        Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones
5                                           Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCSpeakers
6                        Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|Webcams&VoIPEquipment|Webcams
7                                Computers&Accessories|Accessories&Peripherals|Cables&Accessories|CableConnectionProtectors
8                                         Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|DVICables
9                                    Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|EthernetCables
10                                       Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|SATACables
11                                        Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables
12                                                               Computers&Accessories|Accessories&Peripherals|HardDiskBags
13                                               Computers&Accessories|Accessories&Peripherals|HardDriveAccessories|Caddies
14                                 Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets
15            Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers
16             Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|MousePads
17                             Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MouseSets
18                                      Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboards
19                                           Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice
20                                                          Computers&Accessories|Accessories&Peripherals|LaptopAccessories
21                     Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Bags&Sleeves|LaptopSleeves&Slipcases
22                                      Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CameraPrivacyCovers
23                                              Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CoolingPads
24                                                 Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Lapdesks
25                             Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies
26                                   Computers&Accessories|Accessories&Peripherals|LaptopAccessories|NotebookComputerStands
27                                               Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads
28                                        Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingKeyboards
29                                             Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingMice
30                                               Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Headsets
31                                 Computers&Accessories|Accessories&Peripherals|TabletAccessories|Bags,Cases&Sleeves|Cases
32                                         Computers&Accessories|Accessories&Peripherals|TabletAccessories|ScreenProtectors
33                                                   Computers&Accessories|Accessories&Peripherals|TabletAccessories|Stands
34                                                 Computers&Accessories|Accessories&Peripherals|UninterruptedPowerSupplies
35                                                           Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps
36                                                                    Computers&Accessories|Accessories&Peripherals|USBHubs
37                                                                      Computers&Accessories|Components|InternalHardDrives
38                                                                Computers&Accessories|Components|InternalSolidStateDrives
39                                                                                  Computers&Accessories|Components|Memory
40                                                      Computers&Accessories|ExternalDevices&DataStorage|ExternalHardDisks
41                                              Computers&Accessories|ExternalDevices&DataStorage|ExternalMemoryCardReaders
42                                               Computers&Accessories|ExternalDevices&DataStorage|ExternalSolidStateDrives
43                                                              Computers&Accessories|ExternalDevices&DataStorage|PenDrives
44                                                                         Computers&Accessories|Laptops|TraditionalLaptops
45                                                                                           Computers&Accessories|Monitors
46                                                                                  Computers&Accessories|NetworkingDevices
47                                                                Computers&Accessories|NetworkingDevices|DataCards&Dongles
48                                                Computers&Accessories|NetworkingDevices|NetworkAdapters|BluetoothAdapters
49                                                 Computers&Accessories|NetworkingDevices|NetworkAdapters|PowerLANAdapters
50                                              Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters
51                                                              Computers&Accessories|NetworkingDevices|Repeaters&Extenders
52                                                                          Computers&Accessories|NetworkingDevices|Routers
53                               Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges
54                             Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkRefills&Kits
55                                   Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|TonerCartridges
56                                                                 Computers&Accessories|Printers,Inks&Accessories|Printers
57                                                  Computers&Accessories|Printers,Inks&Accessories|Printers|InkjetPrinters
58                                                                                            Computers&Accessories|Tablets
59                                                                              Electronics|Accessories|MemoryCards|MicroSD
60                                                                   Electronics|Accessories|MemoryCards|SecureDigitalCards
61                                           Electronics|Cameras&Photography|Accessories|Batteries&Chargers|BatteryChargers
62                                                        Electronics|Cameras&Photography|Accessories|Cleaners|CleaningKits
63                                                                         Electronics|Cameras&Photography|Accessories|Film
64           Electronics|Cameras&Photography|Accessories|PhotoStudio&Lighting|PhotoBackgroundAccessories|BackgroundSupports
65                                         Electronics|Cameras&Photography|Accessories|Tripods&Monopods|CompleteTripodUnits
66                                      Electronics|Cameras&Photography|Accessories|Tripods&Monopods|Tabletop&TravelTripods
67                                                  Electronics|Cameras&Photography|Accessories|Tripods&Monopods|TripodLegs
68                                                           Electronics|Cameras&Photography|Flashes|Macro&RinglightFlashes
69                                                              Electronics|Cameras&Photography|SecurityCameras|DomeCameras
70                                                                             Electronics|Cameras&Photography|VideoCameras
71                                                                      Electronics|GeneralPurposeBatteries&BatteryChargers
72                                                  Electronics|GeneralPurposeBatteries&BatteryChargers|DisposableBatteries
73                                                Electronics|GeneralPurposeBatteries&BatteryChargers|RechargeableBatteries
74                                                                      Electronics|Headphones,Earbuds&Accessories|Adapters
75                                                                         Electronics|Headphones,Earbuds&Accessories|Cases
76                                                                       Electronics|Headphones,Earbuds&Accessories|Earpads
77                                                             Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear
78                                                             Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear
79                                                           Electronics|Headphones,Earbuds&Accessories|Headphones|Over-Ear
80                                                                               Electronics|HomeAudio|Accessories|Adapters
81                                                              Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts
82                                                             Electronics|HomeAudio|MediaStreamingDevices|StreamingClients
83                                                                         Electronics|HomeAudio|Speakers|BluetoothSpeakers
84                                                                  Electronics|HomeAudio|Speakers|MultimediaSpeakerSystems
85                                                                           Electronics|HomeAudio|Speakers|OutdoorSpeakers
86                                                                          Electronics|HomeAudio|Speakers|SoundbarSpeakers
87                                                                             Electronics|HomeAudio|Speakers|TowerSpeakers
88                                                                   Electronics|HomeTheater,TV&Video|Accessories|3DGlasses
89                                                           Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables
90                                                        Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables
91                                                            Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables
92                                                        Electronics|HomeTheater,TV&Video|Accessories|Cables|SpeakerCables
93                                                              Electronics|HomeTheater,TV&Video|Accessories|RemoteControls
94                             Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts
95                                                                  Electronics|HomeTheater,TV&Video|AVReceivers&Amplifiers
96                                                                              Electronics|HomeTheater,TV&Video|Projectors
97                                                   Electronics|HomeTheater,TV&Video|SatelliteEquipment|SatelliteReceivers
98                                                            Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions
99                                                         Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions
100                                         Electronics|Mobiles&Accessories|MobileAccessories|AutomobileAccessories|Cradles
101                                           Electronics|Mobiles&Accessories|MobileAccessories|Cables&Adapters|OTGAdapters
102                                               Electronics|Mobiles&Accessories|MobileAccessories|Cases&Covers|BasicCases
103                                           Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers
104                                                   Electronics|Mobiles&Accessories|MobileAccessories|Chargers|PowerBanks
105                                                 Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers
106                                                                 Electronics|Mobiles&Accessories|MobileAccessories|Décor
107                                                     Electronics|Mobiles&Accessories|MobileAccessories|Décor|PhoneCharms
108                           Electronics|Mobiles&Accessories|MobileAccessories|Maintenance,Upkeep&Repairs|ScreenProtectors
109                                            Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Bedstand&DeskMounts
110                                                Electronics|Mobiles&Accessories|MobileAccessories|Mounts|HandlebarMounts
111                                              Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Shower&WallMounts
112              Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Flashes&SelfieLights|SelfieLights
113                                   Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|SelfieSticks
114                                        Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Tripods
115                                                                Electronics|Mobiles&Accessories|MobileAccessories|Stands
116                                                            Electronics|Mobiles&Accessories|MobileAccessories|StylusPens
117                                                   Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|BasicMobiles
118                                                    Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones
119                                                                            Electronics|PowerAccessories|SurgeProtectors
120                                                                             Electronics|WearableTechnology|SmartWatches
121                   Health&PersonalCare|HomeMedicalSupplies&Equipment|HealthMonitors|WeighingScales|DigitalBathroomScales
122                                         Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pencils|WoodenPencils
123                                                          Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pens
124                                                                           Home&Kitchen|CraftMaterials|PaintingMaterials
125                                                                    Home&Kitchen|CraftMaterials|PaintingMaterials|Paints
126                                                                           Home&Kitchen|CraftMaterials|Scrapbooking|Tape
127                                     Home&Kitchen|Heating,Cooling&AirQuality|AirConditioners|Split-SystemAirConditioners
128                                                   Home&Kitchen|Heating,Cooling&AirQuality|AirPurifiers|HEPAAirPurifiers
129                                                                Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans
130                                                                Home&Kitchen|Heating,Cooling&AirQuality|Fans|ExhaustFans
131                                                               Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans
132                                                                  Home&Kitchen|Heating,Cooling&AirQuality|Fans|TableFans
133                                                                     Home&Kitchen|Heating,Cooling&AirQuality|Humidifiers
134                                          Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories
135                                                                     Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters
136                                                     Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|ElectricHeaters
137                                                          Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters
138                                                      Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HalogenHeaters
139                                                      Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HeatConvectors
140                                              Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|ImmersionRods
141                                        Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|InstantWaterHeaters
142                                        Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|StorageWaterHeaters
143                               Home&Kitchen|HomeStorage&Organization|LaundryOrganization|IroningAccessories|SprayBottles
144                                                   Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBags
145                                                Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBaskets
146                                               Home&Kitchen|Kitchen&Dining|KitchenTools|ManualChoppers&Chippers|Choppers
147                                 Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeGrinders|ElectricGrinders
148                          Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons
149                                                   Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses
150                                              Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|DripCoffeeMachines
151                                                Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|EspressoMachines
152                                                    Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|MilkFrothers
153                                            Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|StovetopEspressoPots
154                                Home&Kitchen|Kitchen&HomeAppliances|SewingMachines&Accessories|Sewing&EmbroideryMachines
155                                                              Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances
156                                      Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DeepFatFryers|AirFryers
157                                         Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales
158                           Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales|DigitalScales
159                                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|EggBoilers
160                                                 Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandBlenders
161                                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers
162                                             Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|InductionCooktop
163                                          Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|JuicerMixerGrinders
164                                                      Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers
165                                     Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers|ColdPressJuicers
166                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|ElectricKettles
167                Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|Kettle&ToasterSets
168                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Mills&Grinders|WetGrinders
169                                  Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MiniFoodProcessors&Choppers
170                                                Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders
171                                            Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|OvenToasterGrills
172                                               Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Pop-upToasters
173                                            Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers
174                                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers
175                                               Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SandwichMakers
176                              Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories
177        Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories|StandMixerAccessories
178                                                  Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers
179                                                Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|VacuumSealers
180                                           Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons
181                                                 Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|YogurtMakers
182                   Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons
183                 Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|SteamIrons
184                      Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|LintShavers
185                        Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|PressureWashers,Steam&WindowCleaners
186 Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags
187                   Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|CanisterVacuums
188                   Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|HandheldVacuums
189                    Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|RoboticVacuums
190                    Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|Wet-DryVacuums
191                                          Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterCartridges
192                                   Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterFilters&Purifiers
193                                 Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterPurifierAccessories
194                                                                       HomeImprovement|Electrical|Adapters&Multi-Outlets
195                                                                               HomeImprovement|Electrical|CordManagement
196                                                                                MusicalInstruments|Microphones|Condenser
197                                                                      OfficeProducts|OfficeElectronics|Calculators|Basic
198                                                         OfficeProducts|OfficeElectronics|Calculators|Financial&Business
199                                                                 OfficeProducts|OfficeElectronics|Calculators|Scientific
200                                               OfficeProducts|OfficePaperProducts|Paper|Copy&PrintingPaper|ColouredPaper
201                                       OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries
202                  OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|CompositionNotebooks
203                    OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|Notepads&MemoBooks
204                    OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks
205                OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|BottledInk
206              OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|FountainPens
207      OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|GelInkRollerballPens
208   OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens
209  OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|RetractableBallpointPens
210        OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|StickBallpointPens
211                                                   Toys&Games|Arts&Crafts|Drawing&PaintingSupplies|ColouringPens&Markers
    discount_percentage
1             42.000000
2             78.500000
3             35.000000
4             56.500000
5             46.500000
6             44.500000
7             90.000000
8             55.000000
9             54.000000
10            65.000000
11            59.377682
12            54.333333
13            75.000000
14            60.818182
15            87.500000
16            61.250000
17            32.100000
18            35.000000
19            42.041667
20            44.000000
21            61.833333
22            25.666667
23            45.000000
24            58.928571
25            61.000000
26            75.666667
27            52.333333
28            39.000000
29            33.500000
30            56.666667
31            70.500000
32            63.800000
33            70.000000
34            20.000000
35            16.000000
36            43.400000
37            80.000000
38            48.000000
39            49.000000
40            27.000000
41            45.000000
42            68.000000
43            56.900000
44            38.000000
45            50.500000
46            66.000000
47            35.000000
48            33.000000
49            40.000000
50            49.111111
51            54.333333
52            44.666667
53            13.000000
54            73.000000
55            48.000000
56            13.666667
57            11.500000
58            29.000000
59            58.846154
60            44.000000
61            25.000000
62            40.000000
63             0.000000
64            46.000000
65            38.000000
66            69.500000
67            62.500000
68            60.000000
69            42.600000
70            75.000000
71            23.500000
72            14.285714
73            13.333333
74            88.000000
75            76.000000
76            90.000000
77            58.269231
78            52.375000
79            69.000000
80            65.000000
81            73.000000
82             0.000000
83            48.500000
84            38.000000
85            56.250000
86            60.000000
87            43.000000
88            23.000000
89            59.791667
90            46.333333
91            50.500000
92            50.000000
93            59.510204
94            51.166667
95            36.000000
96            42.666667
97            51.333333
98            38.285714
99            52.166667
100           60.333333
101           72.000000
102           70.750000
103           58.000000
104           38.000000
105           51.437500
106           73.200000
107           90.000000
108           66.857143
109           74.500000
110           66.000000
111           82.000000
112           51.000000
113           65.400000
114           66.000000
115           76.400000
116           64.625000
117           18.555556
118           23.294118
119           14.000000
120           69.815789
121           53.000000
122            0.000000
123           10.000000
124            0.000000
125            9.333333
126           21.000000
127           43.000000
128           41.000000
129           38.181818
130           24.666667
131           40.000000
132           42.000000
133           39.333333
134           59.000000
135           51.500000
136           36.000000
137           42.450000
138           29.500000
139           27.000000
140           31.777778
141           48.043478
142           45.083333
143           47.000000
144           60.000000
145           44.846154
146           60.000000
147           51.000000
148           56.333333
149           27.000000
150           37.400000
151           17.000000
152           41.333333
153           54.000000
154           40.500000
155           39.000000
156           44.000000
157           53.900000
158           23.500000
159           52.909091
160           41.684211
161           42.000000
162           44.900000
163           44.166667
164           52.500000
165           47.000000
166           39.000000
167           44.230769
168           21.500000
169           41.875000
170           43.962963
171            9.500000
172           13.000000
173           31.800000
174           33.000000
175           32.363636
176            8.000000
177            0.000000
178           48.000000
179           31.428571
180           53.333333
181           55.000000
182           34.250000
183           23.833333
184           51.318182
185           44.333333
186           49.000000
187           28.250000
188           37.750000
189           45.000000
190           43.666667
191            3.000000
192           42.500000
193           40.818182
194           57.000000
195           58.000000
196           46.000000
197            0.000000
198            0.000000
199            2.500000
200            0.000000
201           53.000000
202           12.000000
203           62.000000
204            5.750000
205            5.000000
206            0.000000
207            0.000000
208            5.000000
209           17.500000
210           13.000000
211            0.000000
> 1. Graph for Q1: Distribution of discounts (Histogram)
Error: unexpected symbol in "1. Graph"
> #1. Graph for Q1: Distribution of discounts (Histogram)
> #This graph will show the discount (such as 40%, 50%, or 60%) available on most products.
> hist(my_data$discount_percentage, 
+      main = "Distribution of Product Discounts", 
+      xlab = "Discount Percentage", 
+      col = "skyblue", 
+      border = "white")
> 
> hist
function (x, ...) 
UseMethod("hist")
<bytecode: 0x000001eaa0d107b0>
<environment: namespace:graphics>
> #Graph for Q2: Discount vs. Rating (Scatter Plot)
> plot(my_data$discount_percentage, my_data$rating,
+      main = "Discount Percentage vs Product Rating",
+      xlab = "Discount Percentage",
+      ylab = "Rating",
+      col = "darkorange",
+      pch = 19)
> 
> #Graph for Q3: Top 5 Discounted Categories (Bar Plot)
> cat_discount <- aggregate(discount_percentage ~ category, data = my_data, FUN = mean)
> cat_discount
                                                                                                                   category
1                                                    Car&Motorbike|CarAccessories|InteriorAccessories|AirPurifiers&Ionizers
2                                                   Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters
3                                           Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets
4                                        Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones
5                                           Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCSpeakers
6                        Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|Webcams&VoIPEquipment|Webcams
7                                Computers&Accessories|Accessories&Peripherals|Cables&Accessories|CableConnectionProtectors
8                                         Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|DVICables
9                                    Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|EthernetCables
10                                       Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|SATACables
11                                        Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables
12                                                               Computers&Accessories|Accessories&Peripherals|HardDiskBags
13                                               Computers&Accessories|Accessories&Peripherals|HardDriveAccessories|Caddies
14                                 Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets
15            Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers
16             Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|MousePads
17                             Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MouseSets
18                                      Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboards
19                                           Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice
20                                                          Computers&Accessories|Accessories&Peripherals|LaptopAccessories
21                     Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Bags&Sleeves|LaptopSleeves&Slipcases
22                                      Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CameraPrivacyCovers
23                                              Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CoolingPads
24                                                 Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Lapdesks
25                             Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies
26                                   Computers&Accessories|Accessories&Peripherals|LaptopAccessories|NotebookComputerStands
27                                               Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads
28                                        Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingKeyboards
29                                             Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingMice
30                                               Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Headsets
31                                 Computers&Accessories|Accessories&Peripherals|TabletAccessories|Bags,Cases&Sleeves|Cases
32                                         Computers&Accessories|Accessories&Peripherals|TabletAccessories|ScreenProtectors
33                                                   Computers&Accessories|Accessories&Peripherals|TabletAccessories|Stands
34                                                 Computers&Accessories|Accessories&Peripherals|UninterruptedPowerSupplies
35                                                           Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps
36                                                                    Computers&Accessories|Accessories&Peripherals|USBHubs
37                                                                      Computers&Accessories|Components|InternalHardDrives
38                                                                Computers&Accessories|Components|InternalSolidStateDrives
39                                                                                  Computers&Accessories|Components|Memory
40                                                      Computers&Accessories|ExternalDevices&DataStorage|ExternalHardDisks
41                                              Computers&Accessories|ExternalDevices&DataStorage|ExternalMemoryCardReaders
42                                               Computers&Accessories|ExternalDevices&DataStorage|ExternalSolidStateDrives
43                                                              Computers&Accessories|ExternalDevices&DataStorage|PenDrives
44                                                                         Computers&Accessories|Laptops|TraditionalLaptops
45                                                                                           Computers&Accessories|Monitors
46                                                                                  Computers&Accessories|NetworkingDevices
47                                                                Computers&Accessories|NetworkingDevices|DataCards&Dongles
48                                                Computers&Accessories|NetworkingDevices|NetworkAdapters|BluetoothAdapters
49                                                 Computers&Accessories|NetworkingDevices|NetworkAdapters|PowerLANAdapters
50                                              Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters
51                                                              Computers&Accessories|NetworkingDevices|Repeaters&Extenders
52                                                                          Computers&Accessories|NetworkingDevices|Routers
53                               Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges
54                             Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkRefills&Kits
55                                   Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|TonerCartridges
56                                                                 Computers&Accessories|Printers,Inks&Accessories|Printers
57                                                  Computers&Accessories|Printers,Inks&Accessories|Printers|InkjetPrinters
58                                                                                            Computers&Accessories|Tablets
59                                                                              Electronics|Accessories|MemoryCards|MicroSD
60                                                                   Electronics|Accessories|MemoryCards|SecureDigitalCards
61                                           Electronics|Cameras&Photography|Accessories|Batteries&Chargers|BatteryChargers
62                                                        Electronics|Cameras&Photography|Accessories|Cleaners|CleaningKits
63                                                                         Electronics|Cameras&Photography|Accessories|Film
64           Electronics|Cameras&Photography|Accessories|PhotoStudio&Lighting|PhotoBackgroundAccessories|BackgroundSupports
65                                         Electronics|Cameras&Photography|Accessories|Tripods&Monopods|CompleteTripodUnits
66                                      Electronics|Cameras&Photography|Accessories|Tripods&Monopods|Tabletop&TravelTripods
67                                                  Electronics|Cameras&Photography|Accessories|Tripods&Monopods|TripodLegs
68                                                           Electronics|Cameras&Photography|Flashes|Macro&RinglightFlashes
69                                                              Electronics|Cameras&Photography|SecurityCameras|DomeCameras
70                                                                             Electronics|Cameras&Photography|VideoCameras
71                                                                      Electronics|GeneralPurposeBatteries&BatteryChargers
72                                                  Electronics|GeneralPurposeBatteries&BatteryChargers|DisposableBatteries
73                                                Electronics|GeneralPurposeBatteries&BatteryChargers|RechargeableBatteries
74                                                                      Electronics|Headphones,Earbuds&Accessories|Adapters
75                                                                         Electronics|Headphones,Earbuds&Accessories|Cases
76                                                                       Electronics|Headphones,Earbuds&Accessories|Earpads
77                                                             Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear
78                                                             Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear
79                                                           Electronics|Headphones,Earbuds&Accessories|Headphones|Over-Ear
80                                                                               Electronics|HomeAudio|Accessories|Adapters
81                                                              Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts
82                                                             Electronics|HomeAudio|MediaStreamingDevices|StreamingClients
83                                                                         Electronics|HomeAudio|Speakers|BluetoothSpeakers
84                                                                  Electronics|HomeAudio|Speakers|MultimediaSpeakerSystems
85                                                                           Electronics|HomeAudio|Speakers|OutdoorSpeakers
86                                                                          Electronics|HomeAudio|Speakers|SoundbarSpeakers
87                                                                             Electronics|HomeAudio|Speakers|TowerSpeakers
88                                                                   Electronics|HomeTheater,TV&Video|Accessories|3DGlasses
89                                                           Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables
90                                                        Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables
91                                                            Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables
92                                                        Electronics|HomeTheater,TV&Video|Accessories|Cables|SpeakerCables
93                                                              Electronics|HomeTheater,TV&Video|Accessories|RemoteControls
94                             Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts
95                                                                  Electronics|HomeTheater,TV&Video|AVReceivers&Amplifiers
96                                                                              Electronics|HomeTheater,TV&Video|Projectors
97                                                   Electronics|HomeTheater,TV&Video|SatelliteEquipment|SatelliteReceivers
98                                                            Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions
99                                                         Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions
100                                         Electronics|Mobiles&Accessories|MobileAccessories|AutomobileAccessories|Cradles
101                                           Electronics|Mobiles&Accessories|MobileAccessories|Cables&Adapters|OTGAdapters
102                                               Electronics|Mobiles&Accessories|MobileAccessories|Cases&Covers|BasicCases
103                                           Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers
104                                                   Electronics|Mobiles&Accessories|MobileAccessories|Chargers|PowerBanks
105                                                 Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers
106                                                                 Electronics|Mobiles&Accessories|MobileAccessories|Décor
107                                                     Electronics|Mobiles&Accessories|MobileAccessories|Décor|PhoneCharms
108                           Electronics|Mobiles&Accessories|MobileAccessories|Maintenance,Upkeep&Repairs|ScreenProtectors
109                                            Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Bedstand&DeskMounts
110                                                Electronics|Mobiles&Accessories|MobileAccessories|Mounts|HandlebarMounts
111                                              Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Shower&WallMounts
112              Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Flashes&SelfieLights|SelfieLights
113                                   Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|SelfieSticks
114                                        Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Tripods
115                                                                Electronics|Mobiles&Accessories|MobileAccessories|Stands
116                                                            Electronics|Mobiles&Accessories|MobileAccessories|StylusPens
117                                                   Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|BasicMobiles
118                                                    Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones
119                                                                            Electronics|PowerAccessories|SurgeProtectors
120                                                                             Electronics|WearableTechnology|SmartWatches
121                   Health&PersonalCare|HomeMedicalSupplies&Equipment|HealthMonitors|WeighingScales|DigitalBathroomScales
122                                         Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pencils|WoodenPencils
123                                                          Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pens
124                                                                           Home&Kitchen|CraftMaterials|PaintingMaterials
125                                                                    Home&Kitchen|CraftMaterials|PaintingMaterials|Paints
126                                                                           Home&Kitchen|CraftMaterials|Scrapbooking|Tape
127                                     Home&Kitchen|Heating,Cooling&AirQuality|AirConditioners|Split-SystemAirConditioners
128                                                   Home&Kitchen|Heating,Cooling&AirQuality|AirPurifiers|HEPAAirPurifiers
129                                                                Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans
130                                                                Home&Kitchen|Heating,Cooling&AirQuality|Fans|ExhaustFans
131                                                               Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans
132                                                                  Home&Kitchen|Heating,Cooling&AirQuality|Fans|TableFans
133                                                                     Home&Kitchen|Heating,Cooling&AirQuality|Humidifiers
134                                          Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories
135                                                                     Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters
136                                                     Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|ElectricHeaters
137                                                          Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters
138                                                      Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HalogenHeaters
139                                                      Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HeatConvectors
140                                              Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|ImmersionRods
141                                        Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|InstantWaterHeaters
142                                        Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|StorageWaterHeaters
143                               Home&Kitchen|HomeStorage&Organization|LaundryOrganization|IroningAccessories|SprayBottles
144                                                   Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBags
145                                                Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBaskets
146                                               Home&Kitchen|Kitchen&Dining|KitchenTools|ManualChoppers&Chippers|Choppers
147                                 Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeGrinders|ElectricGrinders
148                          Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons
149                                                   Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses
150                                              Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|DripCoffeeMachines
151                                                Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|EspressoMachines
152                                                    Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|MilkFrothers
153                                            Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|StovetopEspressoPots
154                                Home&Kitchen|Kitchen&HomeAppliances|SewingMachines&Accessories|Sewing&EmbroideryMachines
155                                                              Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances
156                                      Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DeepFatFryers|AirFryers
157                                         Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales
158                           Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales|DigitalScales
159                                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|EggBoilers
160                                                 Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandBlenders
161                                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers
162                                             Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|InductionCooktop
163                                          Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|JuicerMixerGrinders
164                                                      Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers
165                                     Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers|ColdPressJuicers
166                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|ElectricKettles
167                Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|Kettle&ToasterSets
168                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Mills&Grinders|WetGrinders
169                                  Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MiniFoodProcessors&Choppers
170                                                Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders
171                                            Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|OvenToasterGrills
172                                               Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Pop-upToasters
173                                            Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers
174                                                   Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers
175                                               Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SandwichMakers
176                              Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories
177        Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories|StandMixerAccessories
178                                                  Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers
179                                                Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|VacuumSealers
180                                           Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons
181                                                 Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|YogurtMakers
182                   Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons
183                 Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|SteamIrons
184                      Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|LintShavers
185                        Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|PressureWashers,Steam&WindowCleaners
186 Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags
187                   Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|CanisterVacuums
188                   Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|HandheldVacuums
189                    Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|RoboticVacuums
190                    Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|Wet-DryVacuums
191                                          Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterCartridges
192                                   Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterFilters&Purifiers
193                                 Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterPurifierAccessories
194                                                                       HomeImprovement|Electrical|Adapters&Multi-Outlets
195                                                                               HomeImprovement|Electrical|CordManagement
196                                                                                MusicalInstruments|Microphones|Condenser
197                                                                      OfficeProducts|OfficeElectronics|Calculators|Basic
198                                                         OfficeProducts|OfficeElectronics|Calculators|Financial&Business
199                                                                 OfficeProducts|OfficeElectronics|Calculators|Scientific
200                                               OfficeProducts|OfficePaperProducts|Paper|Copy&PrintingPaper|ColouredPaper
201                                       OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries
202                  OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|CompositionNotebooks
203                    OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|Notepads&MemoBooks
204                    OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks
205                OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|BottledInk
206              OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|FountainPens
207      OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|GelInkRollerballPens
208   OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens
209  OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|RetractableBallpointPens
210        OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|StickBallpointPens
211                                                   Toys&Games|Arts&Crafts|Drawing&PaintingSupplies|ColouringPens&Markers
    discount_percentage
1             42.000000
2             78.500000
3             35.000000
4             56.500000
5             46.500000
6             44.500000
7             90.000000
8             55.000000
9             54.000000
10            65.000000
11            59.377682
12            54.333333
13            75.000000
14            60.818182
15            87.500000
16            61.250000
17            32.100000
18            35.000000
19            42.041667
20            44.000000
21            61.833333
22            25.666667
23            45.000000
24            58.928571
25            61.000000
26            75.666667
27            52.333333
28            39.000000
29            33.500000
30            56.666667
31            70.500000
32            63.800000
33            70.000000
34            20.000000
35            16.000000
36            43.400000
37            80.000000
38            48.000000
39            49.000000
40            27.000000
41            45.000000
42            68.000000
